# Generated by Django 6.0.4 on 2026-04-16 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(default='Auto Save', max_length=50)),
                ('guild_state', models.JSONField(default=dict)),
                ('dungeon_state', models.JSONField(blank=True, null=True)),
                ('overworld_state', models.JSONField(blank=True, null=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot'],
                'unique_together': {('user', 'slot')},
            },
        ),
    ]
